### ISSUE TITLE
NPE for untyped property

### ISSUE THREAD

**Issue by bbrockbernd** [JetBrains-Research/kotlinRMiner#12]
In [UMLModelPsiReader](https://github.com/JetBrains-Research/kotlinRMiner/blob/73b6545e049254ace5d9777c713862b46f1da8f1/src/main/java/org/jetbrains/research/kotlinrminer/UMLModelPsiReader.java#L156) fieldDeclaration.getTypeReference() call results in null, when a kotlin property is untyped.

**Comment by onewhl** [comment]
Fixed
